### ISSUE TITLE
Question for the book. what is req.response property?

### ISSUE THREAD

**Issue by junghanChoi** [parripandian/building-nodejs-api-with-tdd-approach#1]
I'm reading your book and I have a question.

I'm reading chapter 9, getCustomer API.
In the customer.middleware.js , there's a statements like this
```
function getCustomerById(req,res,next){
....
   function success(data){
       req.response = data; next();  /// here
}
}
```
I saw the express api [document](https://expressjs.com/ko/4x/api.html#res), but I couldn't find req.response property.
I thought res.send(data) is more profer. But so far, the test passed.
What is 'req.response' property? why not use res.send?

**Comment by parripandian** [comment]
Hi @junghanChoi,

Thanks for reading the book.

The **req.response** is not an out of the box property that comes with the request object.

The **function getCustomerById()** is fetching the customer details for the customerId and setting the result in the request object, **req**, as it's one of the shared objects between the controller and the middleware functions. 

In the middleware function, we are adding a new property, **response**, to the **req** object.
And then, in the controller, we are getting the **req.response** property's value as a JSON response for the API call.

So the **req.response** property is used for just carrying the customer details data from the middleware to the controller.

Below is the controller code which calls the **function getCustomerById()** of the **customer.middleware.js** and returns the response as JSON.

```
router.get('/:customerId',
    CustomerMiddleware.getCustomerById,
    function (req, res) {
        res.status(200).json(req.response);
    }); 
```
---------

Another reason for not using the response object's **res.send(data)** to send the customer details to the API call is as below.

As per this REST API's design/architecture, only the **CustomerController** will be handling the request & response related functionalities. 
The **CustomerMiddleware's** responsibility is to extract the required parameter/query from the request object and invoke the CustomerService to fetch the data from the MongoDB database. 

And finally, middleware sets the fetched data in the request object, **req**, to let the controller respond to the API call with the customer details.

You could find more details about the individual component's roles and responsibilities in the  **6.6.2. Segregation of Duties** section.

Also, we can reuse the **function getCustomerById()** call in another API endpoint in the controller with few more middleware functions added after fetching the customer details as shown below. In this case, not using the **res.send(data)** in the middleware would be beneficial for us.

```
    router.get('/:customerId/email-content',
        CustomerMiddleware.getCustomerById,
        EmailContentMiddleware.getEmailContentToSendToCustomer,
        function (req, res) {
            res.status(200).json(req.emailContentResponse);
        });
```
 
------
Please let me know if it answers your above question.

**Comment by junghanChoi** [comment]
Thank you for your detail explanation!
